### ISSUE TITLE
os-lib like Hadoop filesystem operations

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#1]
@alfonsorr - This project would be a good place to put the os-lib like Hadoop filesystem operations 🤓 

Here's some more context for other interested parties.

There is an [os-lib](https://github.com/com-lihaoyi/os-lib) project that wraps the `java.io` and `java.nio` libraries and allows for [elegant Scala filesystem operations](https://mungingdata.com/scala/filesystem-paths-move-copy-list-delete-folders/).

It'd be nice to build a wrapper around `org.apache.hadoop.fs` that exposes the Hadoop filesystem operations in a similar manner.

```scala
// os-lib line to delete a file
os.remove(os.pwd / "my_folder" / "story.txt")

// code we want to delete a file with Hadoop
hos.remove(hos.pwd / "my_folder" / "story.txt")
```

**Comment by alfonsorr** [comment]
Will put it the next lib on the list 😉

**Comment by brayanjuls** [comment]
@MrPowers - Can I take this ticket?  I would like to propose a solution.  I am not familiar with the os-lib but it would be a good challenge.

**Comment by MrPowers** [comment]
@brayanjuls - yep, give this a shot!  Studying the [os-lib codebase](https://github.com/com-lihaoyi/os-lib) will certainly make you a better Scala programmer!

**Comment by brayanjuls** [comment]
@MrPowers - I have been reading the code of the os-lib and it has pretty interesting ideas and also a few sorceries that I am still figuring out  =). I have an idea for an initial version, let me know what you think. 

Initially, we could have the path wrapper feature and a few file system operations. To implement it we need to create the Path.scala file which will contain:

* **BasePath trait**: abstraction from which we are going to implement absolute and relative paths. It will contain functions like “/“, “ext”, “lastName” and “baseName”. 
* **JodiePath class/object**: this is a wrapper of the for the Hadoop Path class(org.apache.hadoop.fs.Path). It will contain absolute paths and will use implicit conversion to handle different build patterns, we could call this class JodiePath to avoid confusion with all the other existing path classes.  This is similar to the Path in the os-lib.
    * Here I am assuming that all the paths will be a fully-qualified URI: schema://authority/path e.g: `hdfs://nnAddress:nnPort/foo/bar`.
    * This inherited from BasePath
* **PathPart trait/object**: this is a set of implicit conversions used to concatenate paths from different data types. It would enable this, `hio.Path(“root”) / “foo” / relativePath`.
     *  This is used in the JodiePath class by the "/" function.
* **ConvertiblePath trait/object**: this is a type class that enables the creation of Hadoop Paths from different data types. It is used as a parameter of the JodiePath constructor so we can create absolute paths from String, FileStatus, Paths, etc.
    * This is used in the JodiePath object as a parameter by the "apply" function.

Also, we need to create the FSOps.scala file which will contain each operation(mkdir,remove,etcs..) implemented as an object. Initially, we could start with the following operations:
* mkdir(path):unit
* write(path,content):unit
* read(path):String
* list(path):Seq[String]
* remove(path):Unit

Both files Path.scala and FsOps.scala will be under the package object hio which will help to expose the interfaces like this: `hio.Path(“….”)`, `hio.mkdir(“…”)`, `hio.list(“…)` etc.

Some things that I still need to consider:
* Configuration for authentication to filesystems. 
* Support for relative paths also path navigation moving up and down.
* Default directories. root, wd. What should be the default for each when we are accessing a remote location? 
* Permission associated with file/folders when input operations are performed like mkdir, write, etc.
* Access to cloud storage like aws s3?
*  Let me know if you see other things that I am not considering or  I have not mentioned here.

**Comment by MrPowers** [comment]
Everything you're proposing sounds reasonable to me.  To be honest, my Scala skills aren't the best, so I won't be able to give you the most code advice.  I will be able to give you feedback on the intuitiveness of the interface you provide & will be able to get better Scala coders to review the implementation.  Really excited about this!!!
