### ISSUE TITLE
Make it easy to determine if a Spark table is managed / external / not registered in Hive

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#14]
It's not easy to determine if a Spark table is managed, external or not registered in Hive at all.

Perhaps there is a Hive query that makes this easy already.

We should look into this and see if there are better interfaces for end users.

**Comment by brayanjuls** [comment]
I am picking this one first. I will purpose a solution in the following days.

**Comment by MrPowers** [comment]
This was merged.
