### ISSUE TITLE
High level Hive metastore vision

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#16]
Many Spark users are registering tables in a Hive metastore without any idea of what the Hive metastore is, its basic functionality, and best practices for leveraging the Hive metastore.

We should brainstorm how to provide end user interfaces that demystify the Hive metastore for end users.  What tables are registered, what are the paths, which tables are external/managed, etc.

Guidance on how to convert from external => managed and from not registered => external are examples of issues that baffle Spark users, myself included.

The purpose of this issue is to brainstorm the types of interfaces we can provide end users.

**Comment by brayanjuls** [comment]
Issue migrated to diane project, closing it here.
