### ISSUE TITLE
Reorganization of this repo

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#18]
This project serves the following main functions:

* Delta Lake helper methods
* HDFS helper methods
* Hive Helper methods

Here are the dependencies: 

```scala
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.3.1" % "provided"
libraryDependencies += "org.apache.spark" %% "spark-hive" % "3.3.1" % "provided"

libraryDependencies += "io.delta" %% "delta-core" % "2.1.0" % "provided"
libraryDependencies += "com.github.mrpowers" %% "spark-daria" % "0.38.2"
libraryDependencies += "com.github.mrpowers" %% "spark-fast-tests" % "1.0.0" % "test"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"
libraryDependencies += "com.lihaoyi" %% "os-lib" % "0.7.1" % "test"
libraryDependencies += "org.apache.hadoop" % "hadoop-aws" % "3.3.1"
libraryDependencies += "org.apache.hadoop" % "hadoop-azure" % "3.3.1"
libraryDependencies += "com.microsoft.azure" % "azure-data-lake-store-sdk" % "2.3.10"
```

I think we should separate the HDFS functions and Hive functions to separate code repositories, so users can opt into the dependencies they want.  @brayanjuls - do you want to make those separate code repos in your personal GitHub account?  I will obviously be happy to contribute and promote the functionality.

**Comment by brayanjuls** [comment]
I agree with you. I think for practicality, we should make each project fine-scoped. Regarding having them in my GitHub domain I would be glad to do it and maintain it. 

Regarding the Hive helper, those functions currently involve interacting with delta tables, for example determining if a delta table is external/managed, registering a delta table, and creating a view from a delta table, should we extract those functions from Jodie as well?

**Comment by MrPowers** [comment]
@brayanjuls - yea, I think there should be one repo for the Hadoop filesystem operations and another repo for the Hive helper functions.  I think you should make those two libraries and I will definitely promote them 🚀 

Let's meet to brainstorm project names and next steps.  I'll be able to give you some good tips that'll help you maintain these Scala libraries in production.

**Comment by brayanjuls** [comment]
I will take this ticket now to remove the dependencies and create new repositories.

**Comment by MrPowers** [comment]
@brayanjuls - awesome, sounds good!  Feel free to ping me with the suggested repo names before you create them if you'd like.  Otherwise, just go for it.   Really excited this code is going to find the right home.

**Comment by brayanjuls** [comment]
@MrPowers - sure! I will ping you with the names of the repositories for your opinión once I have them.
