### ISSUE TITLE
Implement the function remove duplicate records

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#2]
Port the functions kill_duplicates and drop_duplicates from the mack library to jodie. 

I propose changing the name of the function to removeDuplicateRecords during this implementation, this will end up as an overloaded function, one with the primary key parameter and the other without the primary key.

**Comment by MrPowers** [comment]
@brayanjuls - that proposal sounds good to me!  Looking forward to seeing the PR!

**Comment by brayanjuls** [comment]
@MrPowers  I sent a PR when that one is approved I will go ahead and port the remaining functions.

**Comment by MrPowers** [comment]
This is done, awesome work @brayanjuls
