### ISSUE TITLE
Create command to show all Hive tables

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#20]
It'd be useful to have a Hive command that provides a more elegant way to show all the Hive tables / associated metadata than what's outlined in [this answer](https://stackoverflow.com/questions/35004455/how-to-get-all-table-definitions-in-a-database-in-hive).

Perhaps `HiveHelpers.allTables()` that returns a list of `HiveTable` objects.  The `HiveTable` object can contain the table name, `HiveTableType`, etc.  I'm just making up abstractions that could be cool.  Feel free to implement this however it's best abstracted.

**Comment by ilyasse05** [comment]
Hello all
I am new in spark, but i have more experience in Teradata.
Have a function to get informations about metadata is very helpful, i think also for anothers function like getColumns with type, description or coment, if it is a primay key or if there is zorder on it...

**Comment by MrPowers** [comment]
@ilyasse05 - thanks for the comment.  We will try to add all those helper methods.  Really appreciate the feedback.

**Comment by brayanjuls** [comment]
Issue migrated to diane project, closing it here.
