### ISSUE TITLE
Add automatic code formatting

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#25]
Here are the [old recommended settings](https://github.com/MrPowers/spark-style-guide#automated-code-formatting-tools).  

Here are the [new recommended settings](https://github.com/MrPowers/spark-style-guide/issues/5).  

Interested in the scalafmt settings you think are best for a Scala codebase @brayanjuls.

**Comment by brayanjuls** [comment]
I am taking this one as well.
