### ISSUE TITLE
Save deltaTable in csv, json format with parameter fileName

### ISSUE THREAD

**Issue by ilyasse05** [MrPowers/jodie#30]
Hi,
At work we always need to export or save data from deltaTable to one file csv with separator or json format, with the native spark function we need to specify coalesce(1) to get one file repartition and we add another comand to rename(move + delete old one) the file with a specifique name.

I thing it will be simply for developer to have function save with 3 parameter (dirPath=/dir1/,fileName =Name_data.csv,extention =csv, separator=||)
Wath do you think ?

**Comment by MrPowers** [comment]
Thanks for opening this.

There is a [`DariaWriters.writeSingleFile()` method in the spark-daria library](https://github.com/MrPowers/spark-daria/blob/main/src/main/scala/com/github/mrpowers/spark/daria/sql/DariaWriters.scala) that you might find useful.  I wrote [a blog post on how to use this method here](https://mungingdata.com/apache-spark/output-one-file-csv-parquet/).  

This library is more focused on Delta Lake helper methods.  The method you're alluding to should work on data that's stored in any file format.  Helper method should be invoked with a DataFrame argument to achive this.

So, I think spark-daria is the best place for this particular abstraction.  @brayanjuls is actually building a separate library with Hadoop filesystem helper methods and this functionality might be a good fit there too.

Brayan - any additional thoughts you have on this one?

**Comment by ilyasse05** [comment]
I agree with you but if developers need to import 10 librares for one project it will be not interesting, this is why if we can have one library with a lot of functions, that will be very interesting.

**Comment by brayanjuls** [comment]
@ilyasse05  - I think the downside of having a single library with many functions covering many frameworks is that you normally don't want to have dependencies that you are not using. For example, if we add that function here, someone that want's to use it on a spark data frame and using another table format will have to download the delta dependency even though she doesn't need it.  

@MrPowers - I agree on maintaining the scope of this project. This would be a good fit for spark-daria.

**Comment by MrPowers** [comment]
Thanks for the suggestion, but I don't think this would be a good addition to jodie.
