### ISSUE TITLE
Port the function delta_file_sizes

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#33]
We want to port the function delta_file_sizes from the [mack project](https://github.com/MrPowers/mack). 

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L476 

Reference to the origin of this function: https://github.com/MrPowers/mack/issues/16

**Comment by joydeepbroy-zeotap** [comment]
@brayanjuls @MrPowers shouldn't we close this issue as the code is now merged
