### ISSUE TITLE
Port the function validate_append

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#38]
We want to port the function validate_append from the [mack project](https://github.com/MrPowers/mack).

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L347

Reference to the origin of this function: https://github.com/MrPowers/mack/issues/43

**Comment by chridac95** [comment]
Hey @brayanjuls,  I'd like working on this ticket, could you please assign it to me?

**Comment by jjpulidos** [comment]
Hey @brayanjuls, I'd like working on this ticket.
