### ISSUE TITLE
Port the function is_composite_key_candidate

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#39]
We want to port the function is_composite_key_candidate from the [mack project](https://github.com/MrPowers/mack).

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L432

Reference to the origin of this function: https://github.com/MrPowers/mack/issues/30

**Comment by chridac95** [comment]
@brayanjuls  I'm interested on working on this issue, could you please assign it to me.

**Comment by chridac95** [comment]
@brayanjuls PR created: https://github.com/MrPowers/jodie/pull/78
Could you please review it when you have a chance? Thanks in advance
