### ISSUE TITLE
Port the function find_composite_key_candidates

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#40]
We want to port the function find_composite_key_candidates from the [mack project](https://github.com/MrPowers/mack).

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L543

Reference to the origin of this function: https://github.com/MrPowers/mack/issues/31

**Comment by ilyasse05** [comment]
Hi @brayanjuls 
I think this function is very interesting,
In teradata we have function that help us to find columns that can be candidat to define index or partition for table.
The function give us, for every column [number of unique values, % Number Values devided by total rows of table].
We can also select special columns to get this stats, and also % of sampling rows to calculat stat.

**Comment by brayanjuls** [comment]
@ilyasse05 - a function that return partition candidates seams like an interesting idea, but i think that type of function is not specific of delta, that feature could be implemented in [spark-daria](https://github.com/MrPowers/spark-daria). Maybe it is already implemented. @MrPowers do you know if something like that already exits in spark-daria ?

In the meantime, the function of this issue was already merged so I will close it.
