### ISSUE TITLE
Port the functions humanize_bytes

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#42]
We want to port the function humanize_bytes from the [mack project](https://github.com/MrPowers/mack).

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L521

The purpose of this helper function is to make large numbers of bytes on delta tables human readable.

**Comment by sebastian2296** [comment]
Commenting for reference of [this other issue](https://github.com/MrPowers/jodie/issues/43#issuecomment-1705659451).
