### ISSUE TITLE
port the function show_delta_file_sizes

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#43]
We want to port the function show_delta_file_sizes from the [mack project](https://github.com/MrPowers/mack). This function depends on the function  humanize_bytes, make sure it exits before implementing this.

Here is a link to the function: https://github.com/MrPowers/mack/blob/cf250e29fa366cd7a0d31a0bc55edb1c74ebbd75/mack/__init__.py#L497

This function prints the number of files, the size of the table, and the average file size for a delta table.

**Comment by sebastian2296** [comment]
Hey @brayanjuls, I'd like to tackle this one. Since it depends on implementing [humanize_bytes](https://github.com/MrPowers/jodie/issues/42) , I could work on that issue as well.

**Comment by brayanjuls** [comment]
@sebastian2296  - sure! I am going to assign both of them to you.
