### ISSUE TITLE
Add Licensing

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#50]
To keep it simple we could use MIT License.

**Comment by MrPowers** [comment]
@brayanjuls - Yea, MIT License sounds good to me.

**Comment by ilyasse05** [comment]
Why MIT License ?!

**Comment by brayanjuls** [comment]
The MIT license allows for code use in any project, for software distribution, monetization, etc. It is similar to Apache 2.0 the difference is that Apache has specific rules and use legal jargon but both are permissive.
