### ISSUE TITLE
Publish versions of Jodie for different versions of Scala to Maven

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#52]
Right now we're just publishing for Scala 2.12.

We should also also publish for Scala 2.13.  Is Scala 2.11 still needed?

**Comment by brayanjuls** [comment]
@MrPowers - Looking at these statistics I think we could support scala 2.12 and 2.13, and not 2.11 as its use is decreasing over the years and is under 15% according to the article. https://www.jetbrains.com/lp/devecosystem-2022/scala/

**Comment by brayanjuls** [comment]
This is merged so I would close it.

**Comment by MrPowers** [comment]
Great, thanks @brayanjuls
