### ISSUE TITLE
Add all README examples to a Jupyter Notebook

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#59]
We should have a Jupyter Notebook with all the README examples.  That way users can easily run all the README examples on their local machine and play around with jodie.

We can add this demo notebook to [delta-examples/notebooks/scala](https://github.com/MrPowers/delta-examples/tree/master/notebooks/scala).

Hopefully showing users how easy it is to use jodie in Jupyter notebooks will also attract users.

**Comment by MrPowers** [comment]
@brayanjuls - would you like to grab this one?

**Comment by brayanjuls** [comment]
sure! I would take this one.
