### ISSUE TITLE
Fix Remove Duplicates README

### ISSUE THREAD

**Issue by brayanjuls** [MrPowers/jodie#61]
Currently the we are using the same function example for the two versions.

```scala
DeltaHelpers.removeDuplicateRecords(
  deltaTable = deltaTable,
  primaryKey = "id",
  duplicateColumns = Seq("firstname","lastname")
) 
```

**Comment by MrPowers** [comment]
@brayanjuls - let's pair soon and take another pass at the README.  It's one of the most important ways for us to grow this project.  We need to make sure to have an absolutely beautiful README to attract new users.

**Comment by MrPowers** [comment]
This was fixed.
