### ISSUE TITLE
Make v0.1.0 release

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#67]
Seems like we should make a new release.  You cool with me making the v0.1.0 release @brayanjuls?  This will allow @joydeepbroy-zeotap to write content and reference a Jodie version with the CDF code.

**Comment by brayanjuls** [comment]
@MrPowers - Yes, go ahead.

**Comment by MrPowers** [comment]
@joydeepbroy-zeotap - I am getting the error in the screenshot when I try to deploy.  Any thoughts on how to fix?

![Uploading Screen Shot 2023-03-14 at 12.11.43 PM.png…]()

**Comment by MrPowers** [comment]
<img width="1440" alt="Screen Shot 2023-03-14 at 12 11 43 PM" src="https://user-images.githubusercontent.com/2722395/225084909-37062c29-f901-49c8-a9d4-978049419e83.png">

**Comment by brayanjuls** [comment]
@MrPowers - This is weird because it passed the CI pipeline. Could it be something related to the Scala version that you have in your local environment ?

In case it is an actual issue, we should add a validation for that in our CI pipeline.

**Comment by joydeepbroy-zeotap** [comment]
@brayanjuls true, might be related to local like I got the one for spark when the internet was not connected. @MrPowers there is a breakable loop I am using that returns a `Unit`, I think we can replace that with just a `()` and it should still work

**Comment by MrPowers** [comment]
@brayanjuls - let's setup the CI to run the tests on a matrix of Scala / Spark / Delta Lake versions, see here for an example: https://github.com/MrPowers/spark-fast-tests/blob/main/.github/workflows/ci.yml

We're releasing jodie for these Scala versions and should make sure it's working properly: `crossScalaVersions := Seq("2.12.17", "2.13.10")`

Thanks for the help!

**Comment by brayanjuls** [comment]
@MrPowers - I think we are ready to publish the next release 0.1.0. The tests are currently working as expected and we have a couple of features added since our first release. what do you think?

**Comment by MrPowers** [comment]
@brayanjuls - yes, let's do it.  Is there anything else I need to merge or should I just go ahead and make the release now?

**Comment by brayanjuls** [comment]
@MrPowers - is all set we just need to release it. After the release, we can update the documentation with the new version.
