### ISSUE TITLE
Document all the public interface functions in the README

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#8]
See the [mack library](https://github.com/MrPowers/mack) for examples.  

We want to clearly highlight all the features of this library.

**Comment by brayanjuls** [comment]
I will take this one.

**Comment by MrPowers** [comment]
@brayanjuls - awesome, thank you!

**Comment by MrPowers** [comment]
Thanks for pushing the update @brayanjuls 🚀
