### ISSUE TITLE
Publish Jodie in Maven

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/jodie#9]
Need to make this library accessible so other people can use it.

**Comment by brayanjuls** [comment]
@MrPowers  - Let me know if you need help with this. I haven't done this before but if you point me to the documentation I can go ahead and do it.

**Comment by MrPowers** [comment]
@brayanjuls - let's pair program on this one.  I can show you my current publishing setup and how we can make it better.  Publishing to Maven isn't the easiest process.

**Comment by MrPowers** [comment]
@brayanjuls - I am actually going to take a stab at this one.  See here for the publishing process I'm currently using with other projects: https://github.com/MrPowers/spark-daria#publishing

Will make sure to get you up to speed on whatever process is used.  I hope your projects and my projects end up using the same exact process.  There are cool ways to make my current process even better and I'll look forward to brainstorming with you!

**Comment by MrPowers** [comment]
@brayanjuls - I ran the publishing command.  It looks like it ran successfully.

I expect the library [to show up here by tomorrow](https://repo1.maven.org/maven2/com/github/mrpowers/).  Will report back and let you know.

**Comment by MrPowers** [comment]
@brayanjuls - it worked: https://repo1.maven.org/maven2/com/github/mrpowers/jodie_2.12/

Going to close this one, so happy it worked the first time!
